
llm:
  api_type: "openai"
  model: "gpt-4o"
  base_url: "https://api.openai.com/v1"
  api_key: "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"

models:
 "gpt-4o-mini":
   api_type: "openai"
   base_url: "https://api.openai.com/v1"
   api_key: "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"
   temperature: 0
 "gpt-4o":
   api_type: "openai"
   base_url: "https://api.openai.com/v1"
   api_key: "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"
   temperature: 0
 "claude-3-5-sonnet-20240620":
   api_type: "anthropic"
   base_url: "https://api.anthropic.com"
   api_key: "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"
   temperature: 0
 "gpt-4-turbo":
   api_type: "openai"
   base_url: "https://api.openai.com/v1"
   api_key: "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"
   temperature: 0
 "o1-mini":
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    api_key: "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"
    temperature: 0
 "deepseek-reasoner":
    api_type: "openai"
    base_url: "https://api.deepseek.com/v1"
    api_key: "sk-509d832659e64e73bcb61fc420bf4910"
    temperature: 0
 "gpt-3.5-turbo-0125":
    api_type: "openai"
    base_url: "https://api.openai.com/v1"
    api_key: "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"
    temperature: 0
 "deepseek-chat":
    api_type: "openai"
    base_url: "https://api.deepseek.com/v1"
    api_key: "sk-509d832659e64e73bcb61fc420bf4910"
    temperature: 0

CALC_USAGE: True